### ISSUE TITLE
Problem with creating form

### ISSUE THREAD

**Issue by Darex1991** [nimbis/cmsplugin-forms-builder#13]
Hi ;) I tried to add cms into the page. But still have the same problem:
<img width="1438" alt="screen shot 2017-01-08 at 19 23 26" src="https://cloud.githubusercontent.com/assets/5881611/21752434/003eb444-d5d8-11e6-963a-397fefd0f1a0.png">
What I did wrong? I tried branch `master` and `add-cms-3.1.0-migration`

*EDIT*
When I changed in template:
`<form action='/contact-form/' method="post"`
its render me error :
<img width="634" alt="screen shot 2017-01-08 at 19 52 29" src="https://cloud.githubusercontent.com/assets/5881611/21752608/087c3e52-d5dc-11e6-9a7f-15f4cd27c1cf.png">

**Comment by Colleoni** [comment]
I have encoutered the same problem

**Comment by amadornimbis** [comment]
I'm not sure that I have enough information to attempt to reproduce this. It seems like this might be a Django CMS configuration problem? I can try to add a minimal testing project to this app when I can get a chance within the next few days.

**Comment by Colleoni** [comment]
Actually I found the problem and you are right it is a configuration problem. 
simply need to add forms_builder to urls. py

```
import forms_builder.forms.urls

urlpatterns += i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  
    url(r'^forms/', include(forms_builder.forms.urls)),
    url(r'^', include('cms.urls')),
)
```
Adding it to the readme file of the repo will be enought:)

Best regards,
    Luca

**Comment by Darex1991** [comment]
@Colleoni you are use ajax for this form?

**Comment by Darex1991** [comment]
@Colleoni you have right.
Fix for using sample:
1) add into your urls.py
`url(r'^forms/', include(forms_builder.forms.urls)),`
example -post Colleoni
2) install bootstrap3 and add into `build_form.html`
`{% load sekizai_tags bootstrap3 %}`
