### ISSUE TITLE
Missing README.md in PyPi release v.1.0.0

### ISSUE THREAD

**Issue by makukha** [nimbis/cmsplugin-forms-builder#2]
The file README.md is missing in package version 1.0.0 released on PyPi.
> pip install cmsplugin-forms-builder
> ...
> FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by electroniceagle** [comment]
Should be fixed in v1.0.1.  Also, you may need to remove `url(r'^forms/', include('cmsplugin_forms_builder.urls')` from your urls.py.

**Comment by makukha** [comment]
Thanks, v1.0.1 is OK.
